### ISSUE TITLE
Java 9 compatibility

### ISSUE THREAD

**Issue by hakanai** [ben-manes/concurrentlinkedhashmap#48]
concurrentlinkedhashmap-lru shows up in a jdeps report of classes that will stop working on Java 9:

```
concurrentlinkedhashmap-lru-1.4.1.jar
   com.googlecode.concurrentlinkedhashmap (concurrentlinkedhashmap-lru-1.4.1.jar)                                            
      -> sun.misc                                           JDK internal API (rt.jar)
```

**Comment by ben-manes** [comment]
In v1.4, I embedded Doug's backport of the JDK8 `ConcurrentHashMap` which has faster performance. However the library can be rebuilt without it easily enough to use the JDK's, as Unsafe is not used otherwise.

I'm hesitant to do anything and instead prefer users migrate to Caffeine.

**Comment by hakanai** [comment]
Yeah. Certainly if I find which library is using this jar, I will go to them and ask them to switch anyway.

**Comment by ben-manes** [comment]
Worst case you can make a custom jar and replace the dependency in your build. Its trivial enough that the Redhat guys did that in #44. But it shouldn't be a problem until JDK10.

**Comment by ben-manes** [comment]
JDK11 will still have Unsafe, so probably won't be gone until JDK17 (3 yr LTS schedule).
