### ISSUE TITLE
massive memory usage with 1024 core machine

### ISSUE THREAD

**Issue by zerovian** [ben-manes/concurrentlinkedhashmap#49]
The allocation algorithm for ConcurrentLinkedHashMap consumes 10's of MB of memory on a 1000 CPU core machine.

Will attach a yourkit screenshot showing the bad allocation.

I have a customer with 1024 core machine.  The readBuffers array becomes allocated at 1024 X 128 which consumes ~20MB of memory which is absurd.

**Comment by zerovian** [comment]
![image](https://cloud.githubusercontent.com/assets/3799244/19893650/41049900-a020-11e6-82ec-2fe76b9728b9.png)

**Comment by zerovian** [comment]
This library is included with apache camel and apache activemq, both of which, when used on a machine (Solaris T5) with 1000+ cores end up using an unwieldly amount of memory.  in this instance Apache Camel  creates multiple maps each of which consume 20+MB of memory.  End result is a basic apache activemq setup consumes 300+ MB of memory. (I will log a separate bug with activemq for this)

**Comment by ben-manes** [comment]
I think this was fixed in #43 (v1.4.2). I hadn't realized how excessive the padding accidentally was. Can you check the version used?

In Caffeine I rewrote it to dynamically allocate buffers based on contention which should also help avoid this type of problem.

**Comment by zerovian** [comment]
Can't update this directly since I"m using activemq-all s.jar, and it is embedded in that as part of Camel.  Would need to have camel update to 1.4.2 (it seems to be using 1.4.1 at the moment).

(If I'm reading this right) Your request for upgrade to 1.4.2  https://issues.apache.org/jira/browse/OFBIZ-6747 is still open.

**Comment by ben-manes** [comment]
Fixed in [CAMEL-8994](https://issues.apache.org/jira/browse/CAMEL-8994) and only affected v1.4 releases. Previous ones did not have the padding, so OFBIZ shouldn't be impacted. I can't find usage in ActiveMQ yet, so not sure what version it might be pulling in.

**Comment by ben-manes** [comment]
Oh, I see. It sounds like ActiveMQ needs to update their version of Camel in the all-jar?

**Comment by ben-manes** [comment]
The latest release uses camel 2.16.3, whose [parent-pom](http://repo1.maven.org/maven2/org/apache/camel/camel-parent/2.16.3/camel-parent-2.16.3.pom) shows it to use 1.4.2. Maybe you need to update the activemq dependency?

**Comment by zerovian** [comment]
The dependency was against an older version of our product that we already shipped (slow release cycle).  We will get them a newer version as well.

Also, I'm going to log a bug against orientdb which we are also using 1.4.1 for their profiler which we are also using.

Thanks for tracking this down.

**Comment by ben-manes** [comment]
Sorry for the inconvenience this caused. I sadly never had a 1,000 core machine to test with :)

Please close when you're comfortable that 1.4.2 resolves the issue.

**Comment by zerovian** [comment]
Will close for now as it looks like the CAMEL-8994 is exactly what we've run into.

I'm really sorry you don't have a 1024 core machine. Everyone should have one.
